// Code generated by goctl. DO NOT EDIT.
// Source: third.proto

package server

import (
	"context"

	"jekka-api-go/app/third/cmd/rpc/internal/logic"
	"jekka-api-go/app/third/cmd/rpc/internal/svc"
	"jekka-api-go/app/third/cmd/rpc/third"
)

type ThirdServer struct {
	svcCtx *svc.ServiceContext
	third.UnimplementedThirdServer
}

func NewThirdServer(svcCtx *svc.ServiceContext) *ThirdServer {
	return &ThirdServer{
		svcCtx: svcCtx,
	}
}

// 查询商品详情
func (s *ThirdServer) ProductDetail(ctx context.Context, in *third.ProductDetailReq) (*third.ProductDetailResp, error) {
	l := logic.NewProductDetailLogic(ctx, s.svcCtx)
	return l.ProductDetail(in)
}

// 店铺商品列表
func (s *ThirdServer) ProductList(ctx context.Context, in *third.ProductListReq) (*third.ProductListResp, error) {
	l := logic.NewProductListLogic(ctx, s.svcCtx)
	return l.ProductList(in)
}
