// Code generated by goctl. DO NOT EDIT.
// Source: greet.proto

package server

import (
	"context"

	"jekka-api-go/app/greet/cmd/rpc/greet"
	"jekka-api-go/app/greet/cmd/rpc/internal/logic"
	"jekka-api-go/app/greet/cmd/rpc/internal/svc"
)

type GreetServer struct {
	svcCtx *svc.ServiceContext
	greet.UnimplementedGreetServer
}

func NewGreetServer(svcCtx *svc.ServiceContext) *GreetServer {
	return &GreetServer{
		svcCtx: svcCtx,
	}
}

func (s *GreetServer) SendMessage(ctx context.Context, in *greet.SendMessageReq) (*greet.SendMessageResp, error) {
	l := logic.NewSendMessageLogic(ctx, s.svcCtx)
	return l.SendMessage(in)
}
