// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.6

package types

type AsyncShopBasicDataReq struct {
	JkShopId int64 `json:"jk_shop_id"`
	JkUserId int64 `json:"jk_user_id"`
}

type AsyncShopBasicDataResp struct {
}

type SyncWebhookOrderReq struct {
	JkShopId int64  `json:"jk_shop_id"`
	JkUserId int64  `json:"jk_user_id"`
	OrderId  string `json:"order_id"`
}

type SyncWebhookOrderResp struct {
}
