package shop

// CountryCodeNameMap 国家代码与名称映射
var CountryCodeNameMap = map[string]string{
	"AE": "United Arab Emirates",
	"AL": "Albania",
	"BE": "Belgium",
	"CA": "Canada",
	"CH": "Switzerland",
	"CL": "Chile",
	"CN": "China",
	"DE": "Germany",
	"ES": "Spain",
	"FI": "Finland",
	"FR": "France",
	"GB": "United Kingdom",
	"HK": "Hong Kong",
	"ID": "Indonesia",
	"IL": "Israel",
	"IN": "India",
	"IT": "Italy",
	"KR": "South Korea",
	"MA": "Morocco",
	"MY": "Malaysia",
	"NO": "Norway",
	"PK": "Pakistan",
	"PL": "Poland",
	"SG": "Singapore",
	"SI": "Slovenia",
	"TH": "Thailand",
	"US": "United States",
	"VN": "Vietnam",
	"ZA": "South Africa",
	"PH": "Philippines",
	"AU": "Australia", // 20240816新增
	"JP": "Japan",
	"TW": "Taiwan",
	"KH": "Cambodia",
	"BR": "Brazil",
	"AR": "Argentina",
	"PS": "Palestine",
	"CZ": "Czechia",
	"NL": "Netherlands",
	"AT": "Austria",
	"GR": "Greece",
	"RU": "Russia",
	"SE": "Sweden",
	"CO": "Colombia",
	"DK": "Denmark",
	"PT": "Portugal",
	"GH": "Ghana",
	"CM": "Cameroon",
	"TR": "Turkey",
	"JO": "Jordan",
	"RO": "Romania",
	"KE": "Kenya",
	"IE": "Ireland",
	"UG": "Uganda",
	"AM": "Armenia",
	"TZ": "Tanzania",
	"BI": "Burundi",
	"LU": "Luxembourg",
	"BG": "Bulgaria",
	"UA": "Ukraine",
	"EG": "Egypt",
	"QA": "Qatar",
	"MD": "Moldova",
	"SC": "Seychelles",
	"IQ": "Iraq",
	"VA": "Holy See",
	"LV": "Latvia",
	"EE": "Estonia",
	"IS": "Iceland",
	"IR": "Iran",
	"GE": "Georgia",
	"SK": "Slovakia",
	"KZ": "Kazakhstan",
	"LT": "Lithuania",
	"NZ": "New Zealand",
	"HR": "Croatia",
	"MX": "Mexico",
	"HU": "Hungary",
	"SA": "Saudi Arabia",
	"MT": "Malta",
	"CY": "Cyprus",
	"BH": "Bahrain",
	"SY": "Syrian Arab Republic",
	"LB": "Lebanon",
	"AX": "Aland Islands",
	"ZM": "Zambia",
	"OM": "Oman",
	"RS": "Serbia",
	"MK": "North Macedonia",
	"LI": "Liechtenstein",
	"JE": "Jersey",
	"BA": "Bosnia and Herzegovina",
	"AZ": "Azerbaijan",
	"PE": "Peru",
	"KG": "Kyrgyzstan",
	"RE": "Reunion",
	"IM": "Isle of Man",
	"GG": "Guernsey",
	"GI": "Gibraltar",
	"LY": "Libya",
	"PA": "Panama",
	"YE": "Yemen",
	"BY": "Belarus",
	"UZ": "Uzbekistan",
	"YT": "Mayotte",
	"MQ": "Martinique",
	"GP": "Guadeloupe",
	"MF": "Saint Martin",
	"GF": "French Guiana",
	"KW": "Kuwait",
	"LK": "Sri Lanka",
	"SZ": "Eswatini",
	"CD": "Congo",
	"BD": "Bangladesh",
	"BT": "Bhutan",
	"BN": "Brunei Darussalam",
	"PM": "Saint Pierre and Miquelon",
	"LA": "Laos",
	"GU": "Guam",
	"MP": "Northern Mariana Islands",
	"DO": "Dominican Republic",
	"NG": "Nigeria",
	"EC": "Ecuador",
	"VE": "Venezuela",
	"CR": "Costa Rica",
	"PR": "Puerto Rico",
	"BO": "Bolivia",
	"VI": "Virgin Islands",
	"MN": "Mongolia",
	"TV": "Tuvalu",
	"MV": "Maldives",
	"CC": "Cocos (Keeling) Islands",
	"PG": "Papua New Guinea",
	"TL": "Timor-Leste",
	"SB": "Solomon Islands",
	"VU": "Vanuatu",
	"FJ": "Fiji",
	"CK": "Cook Islands",
	"TO": "Tonga",
	"NP": "Nepal",
	"MO": "Macao",
	"NI": "Nicaragua",
	"JM": "Jamaica",
	"TT": "Trinidad and Tobago",
	"SS": "South Sudan",
	"AF": "Afghanistan",
	"GD": "Grenada",
	"VG": "Virgin Islands",
	"KN": "Saint Kitts and Nevis",
	"AG": "Antigua and Barbuda",
	"BL": "Saint Barthelemy",
	"VC": "Saint Vincent and The Grenadines",
	"BS": "Bahamas",
	"DM": "Dominica",
	"KY": "Cayman Islands",
	"MM": "Myanmar",
	"UY": "Uruguay",
	"ME": "Montenegro",
	"BB": "Barbados",
	"PY": "Paraguay",
	"GT": "Guatemala",
	"UM": "United States",
	"TK": "Tokelau",
	"NC": "New Caledonia",
	"WF": "Wallis and Futuna",
	"AQ": "Antarctica",
	"SM": "San Marino",
	"HN": "Honduras",
	"BZ": "Belize",
	"SV": "El Salvador",
	"AD": "Andorra",
	"MC": "Monaco",
	"TJ": "Tajikistan",
	"FO": "Faroe Islands",
	"CV": "Cabo Verde",
	"BW": "Botswana",
	"ML": "Mali",
	"MZ": "Mozambique",
	"CI": "Cote D'ivoire",
	"ZW": "Zimbabwe",
	"LR": "Liberia",
	"MU": "Mauritius",
	"TN": "Tunisia",
	"MG": "Madagascar",
	"AO": "Angola",
	"NA": "Namibia",
	"SD": "Sudan",
	"MW": "Malawi",
	"BJ": "Benin",
	"RW": "Rwanda",
	"CG": "Congo",
	"GM": "Gambia",
	"LS": "Lesotho",
	"GN": "Guinea",
	"BF": "Burkina Faso",
	"SO": "Somalia",
	"SL": "Sierra Leone",
	"NE": "Niger",
	"CF": "Central African Republic",
	"TG": "Togo",
	"GA": "Gabon",
	"GQ": "Equatorial Guinea",
	"SN": "Senegal",
	"DZ": "Algeria",
	"MR": "Mauritania",
	"TD": "Chad",
	"KP": "North Korea",
	"CU": "Cuba",
	"HT": "Haiti",
	"GY": "Guyana",
	"ET": "Ethiopia",
	"TM": "Turkmenistan",
}

// CountryCodeCurrencyMap 国家货币代码映射
var CountryCodeCurrencyMap = map[string]string{
	"TH": "THB",
	"VN": "VND",
	"SG": "SGD",
	"PH": "PHP",
	"MY": "MYR",
	"ID": "IDR",
	"US": "USD",
	"GB": "GBP",
	"BR": "BRL",
	"MX": "MXN",
	"CL": "CLP",
	"CO": "COP",
}

// CountryCodeNameCNMap 中文国家名称映射
var CountryCodeNameCNMap = map[string]string{
	"AE": "阿拉伯联合酋长国",
	"AL": "阿尔巴尼亚",
	"BE": "比利",
	"CA": "加拿大",
	"CH": "瑞士",
	"CL": "智利",
	"CN": "中国",
	"DE": "德国",
	"ES": "西班牙",
	"FI": "芬兰",
	"FR": "法国",
	"GB": "英国",
	"HK": "香港",
	"ID": "印度尼西亚",
	"IL": "以色列",
	"IN": "印度",
	"IT": "意大利",
	"KR": "南韩",
	"MA": "摩洛哥",
	"MY": "马来西亚",
	"NO": "挪威",
	"PK": "巴基斯坦",
	"PL": "波兰",
	"SG": "新加坡",
	"SI": "斯洛文尼亚",
	"TH": "泰国",
	"US": "美国",
	"VN": "越南",
	"ZA": "南非",
	"PH": "菲律宾",
	"AU": "澳大利亚",
	"JP": "日本",
	"TW": "台湾",
	"KH": "柬埔寨",
	"BR": "巴西",
	"AR": "阿根廷",
	"PS": "巴勒斯坦",
	"CZ": "捷克",
	"NL": "荷兰",
	"AT": "奥地利",
	"GR": "希腊",
	"RU": "俄罗斯",
	"SE": "瑞典",
	"CO": "哥伦比亚",
	"DK": "丹麦",
	"PT": "葡萄牙",
	"GH": "加纳",
	"CM": "喀麦隆",
	"TR": "土耳其",
	"JO": "约旦",
	"RO": "罗马尼亚",
	"KE": "肯尼亚",
	"IE": "爱尔兰",
	"UG": "乌干达",
	"AM": "亚美尼亚",
	"TZ": "坦桑尼亚",
	"BI": "布隆迪",
	"LU": "卢森堡公国",
	"BG": "保加利亚",
	"UA": "乌克兰",
	"EG": "埃及",
	"QA": "卡塔尔",
	"MD": "摩尔多瓦",
	"SC": "塞舌尔",
	"IQ": "伊拉克",
	"LV": "拉脱维亚",
	"EE": "爱沙尼亚",
	"IS": "冰岛",
	"IR": "伊朗",
	"GE": "格鲁吉亚",
	"SK": "斯洛伐克",
	"KZ": "哈萨克斯坦",
	"LT": "立陶宛",
	"NZ": "新西兰",
	"HR": "克罗地亚",
	"MX": "墨西哥",
	"HU": "匈牙利",
	"SA": "沙特阿拉伯",
	"MT": "马耳他",
	"CY": "塞浦路斯",
	"SY": "阿拉伯叙利亚共和国",
	"LB": "黎巴嫩",
	"ZM": "赞比亚",
	"OM": "阿曼",
	"RS": "塞尔维亚",
	"LI": "列支敦斯登",
	"BA": "波黑",
	"AZ": "阿塞拜疆",
	"PE": "秘鲁",
	"KG": "吉尔吉斯斯坦",
	"LY": "利比亚",
	"PA": "巴拿马",
	"YE": "也门",
	"BY": "白罗斯",
	"UZ": "乌兹别克斯坦",
	"KW": "科威特",
	"LK": "斯里兰卡",
	"SZ": "斯威士兰",
	"CD": "刚果",
	"BD": "孟加拉国",
	"BT": "不丹",
	"LA": "老挝",
	"DO": "多米尼加共和国",
	"NG": "尼日利亚",
	"EC": "厄瓜多尔",
	"VE": "委内瑞拉",
	"CR": "哥斯达黎加",
	"BO": "玻利维亚",
	"MN": "蒙古",
	"TV": "图瓦卢",
	"MV": "马尔代夫",
	"VU": "瓦努阿图",
	"FJ": "斐济",
	"TO": "汤加",
	"NP": "尼泊尔",
	"MO": "澳门",
	"NI": "尼加拉瓜",
	"JM": "牙买加",
	"TT": "特立尼达和多巴哥",
	"SS": "南苏丹",
	"AF": "阿富汗",
	"GD": "格林纳达",
	"VG": "维尔京群岛",
	"KN": "圣基茨和尼维斯",
	"AG": "安提瓜和巴布达",
	"BL": "圣巴泰勒米",
	"VC": "圣文森特和格林纳丁斯",
	"BS": "巴哈马群岛",
	"DM": "多米尼加",
	"KY": "开曼群岛",
	"MM": "缅甸",
	"UY": "乌拉圭",
	"ME": "黑山共和国",
	"BB": "巴巴多斯",
	"PY": "巴拉圭",
	"GT": "危地马拉",
	"UM": "美国",
	"TK": "托克劳",
	"NC": "新喀里多尼亚",
	"WF": "瓦利斯和富图纳",
	"AQ": "南极洲",
	"SM": "圣马力诺",
	"HN": "洪都拉斯",
	"BZ": "伯利兹",
	"SV": "萨尔瓦多",
	"AD": "安道尔",
	"MC": "摩纳哥",
	"TJ": "塔吉克斯坦",
	"FO": "法罗群岛",
	"CV": "佛得角",
	"BW": "博茨瓦纳",
	"ML": "马里",
	"MZ": "莫桑比克",
	"CI": "科特迪瓦",
	"ZW": "津巴布韦",
	"LR": "利比里亚",
	"MU": "毛里求斯",
	"TN": "突尼斯",
	"MG": "马达加斯加",
	"AO": "安哥拉",
	"NA": "纳米比亚",
	"SD": "苏丹",
	"MW": "马拉维",
	"BJ": "贝尔哈",
	"RW": "卢旺达",
	"CG": "刚果",
	"GM": "冈比亚",
	"LS": "莱索托",
	"GN": "几内亚",
	"BF": "布基纳法索",
	"SO": "索马里",
	"SL": "塞拉利昂",
	"NE": "尼日尔",
	"CF": "中非共和国",
	"TG": "多哥",
	"GA": "加蓬",
	"GQ": "赤道几内亚",
	"SN": "塞内加尔",
	"DZ": "阿尔及利亚",
	"MR": "毛里塔尼亚",
	"TD": "乍得",
	"KP": "朝鲜",
	"CU": "古巴",
	"HT": "海地",
	"GY": "圭亚那",
	"ET": "埃塞俄比亚",
	"TM": "土库曼斯坦",
}
