// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.6

package handler

import (
	"net/http"

	"jekka-api-go/app/third/cmd/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthInterceptor},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/shop/asyncBasicData",
					Handler: asyncShopBasicDataHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/shop/asyncWebhookOrder",
					Handler: asyncWebhookOrderHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/shop/syncWebhookOrder",
					Handler: syncWebhookOrderHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1"),
	)
}
