// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameJkConfig = "jk_config"

// JkConfig 配置表
type JkConfig struct {
	ID         int64          `gorm:"column:id;primaryKey;autoIncrement:true;comment:配置ID" json:"id"`             // 配置ID
	TargetType int32          `gorm:"column:target_type;not null;comment:目标类型 0:系统 1:用户 2:店铺" json:"target_type"` // 目标类型 0:系统 1:用户 2:店铺
	TargetID   int64          `gorm:"column:target_id;not null;comment:目标ID(用户ID、店铺ID等)" json:"target_id"`        // 目标ID(用户ID、店铺ID等)
	Name       string         `gorm:"column:name;not null;comment:配置名称" json:"name"`                              // 配置名称
	Value      string         `gorm:"column:value;not null;comment:配置值" json:"value"`                             // 配置值
	CreatedAt  time.Time      `gorm:"column:created_at" json:"created_at"`
	UpdatedAt  time.Time      `gorm:"column:updated_at" json:"updated_at"`
	DeletedAt  gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
}

// TableName JkConfig's table name
func (*JkConfig) TableName() string {
	return TableNameJkConfig
}
