// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameJkShop = "jk_shop"

// JkShop mapped from table <jk_shop>
type JkShop struct {
	ID                           int64          `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"` // ID
	JkUserID                     int64          `gorm:"column:jk_user_id;not null;comment:用户ID" json:"jk_user_id"`    // 用户ID
	ShopNo                       string         `gorm:"column:shop_no;not null;comment:店铺编号" json:"shop_no"`          // 店铺编号
	Email                        string         `gorm:"column:email;comment:邮箱" json:"email"`                         // 邮箱
	Phone                        string         `gorm:"column:phone;comment:手机号" json:"phone"`                        // 手机号
	Name                         string         `gorm:"column:name" json:"name"`
	Alias                        string         `gorm:"column:alias;not null;comment:店铺别名" json:"alias"`                                          // 店铺别名
	Status                       int32          `gorm:"column:status;not null;default:1;comment:店铺状态 0:禁用 1:可用" json:"status"`                    // 店铺状态 0:禁用 1:可用
	AuthStatus                   int32          `gorm:"column:auth_status;not null;default:1;comment:授权状态 1:生效中 2:即将过期 3:已过期" json:"auth_status"` // 授权状态 1:生效中 2:即将过期 3:已过期
	ThirdType                    int32          `gorm:"column:third_type;comment:三方店铺类型 1:Shopify" json:"third_type"`                             // 三方店铺类型 1:Shopify
	ThirdAppID                   int32          `gorm:"column:third_app_id;comment:三方应用ID 1:TT老应用 2:TT新应用" json:"third_app_id"`                   // 三方应用ID 1:TT老应用 2:TT新应用
	ThirdShopID                  string         `gorm:"column:third_shop_id" json:"third_shop_id"`
	ThirdShopURL                 string         `gorm:"column:third_shop_url;comment:三方店铺链接" json:"third_shop_url"`                                                             // 三方店铺链接
	ThirdPluginStatus            int32          `gorm:"column:third_plugin_status;not null;comment:三方插件状态 0:未知 1:打开 2:关闭" json:"third_plugin_status"`                           // 三方插件状态 0:未知 1:打开 2:关闭
	ThirdPluginActivatedAt       time.Time      `gorm:"column:third_plugin_activated_at;comment:三方插件首次激活时间" json:"third_plugin_activated_at"`                                   // 三方插件首次激活时间
	ThirdSession                 string         `gorm:"column:third_session;comment:三方session信息（Shopify调用接口用）" json:"third_session"`                                            // 三方session信息（Shopify调用接口用）
	Extra                        string         `gorm:"column:extra;comment:扩展字段（匹配商品链接，订单链接的正则）" json:"extra"`                                                                 // 扩展字段（匹配商品链接，订单链接的正则）
	CustomizationChatBox         string         `gorm:"column:customization_chat_box;comment:定制化聊天框" json:"customization_chat_box"`                                             // 定制化聊天框
	ViewPrompt                   int32          `gorm:"column:view_prompt;comment:店铺后台是否能看到prompt参数，0否1是" json:"view_prompt"`                                                   // 店铺后台是否能看到prompt参数，0否1是
	AccessToken                  string         `gorm:"column:access_token;comment:访问口令" json:"access_token"`                                                                   // 访问口令
	ExpiredAt                    time.Time      `gorm:"column:expired_at;comment:访问口令有效期（NULL表示无有效期）" json:"expired_at"`                                                        // 访问口令有效期（NULL表示无有效期）
	IsTest                       int32          `gorm:"column:is_test;not null;comment:是否测试店铺 0=否 1=是" json:"is_test"`                                                          // 是否测试店铺 0=否 1=是
	IsKa                         bool           `gorm:"column:is_ka;not null;comment:是否是ka店铺 0=否 1=是" json:"is_ka"`                                                             // 是否是ka店铺 0=否 1=是
	IsBpo                        int32          `gorm:"column:is_bpo;not null;comment:是否是BPO店铺 0=否 1=是" json:"is_bpo"`                                                          // 是否是BPO店铺 0=否 1=是
	IsActive                     int32          `gorm:"column:is_active;not null;comment:是否是活跃店铺 0=否 1=是" json:"is_active"`                                                     // 是否是活跃店铺 0=否 1=是
	LearnPolicyStatus            int32          `gorm:"column:learn_policy_status;not null;comment:是否引用自学习政策 0=否 1=是" json:"learn_policy_status"`                               // 是否引用自学习政策 0=否 1=是
	CountryCode                  string         `gorm:"column:country_code;not null;comment:国家码" json:"country_code"`                                                           // 国家码
	LangCode                     string         `gorm:"column:lang_code;not null;comment:语言码" json:"lang_code"`                                                                 // 语言码
	EmailForTicketRequiredStatus int32          `gorm:"column:email_for_ticket_required_status;not null;comment:生成工单客户邮箱是否必填, 0=否 1=是" json:"email_for_ticket_required_status"` // 生成工单客户邮箱是否必填, 0=否 1=是
	EmailRequiredAfterNthMessage int32          `gorm:"column:email_required_after_nth_message;not null;comment:第N句对话必需提交邮箱, （默认0不需要）" json:"email_required_after_nth_message"` // 第N句对话必需提交邮箱, （默认0不需要）
	CreatedAt                    time.Time      `gorm:"column:created_at" json:"created_at"`
	UpdatedAt                    time.Time      `gorm:"column:updated_at" json:"updated_at"`
	DeletedAt                    gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
}

// TableName JkShop's table name
func (*JkShop) TableName() string {
	return TableNameJkShop
}
