// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameJkThirdOrder = "jk_third_order"

// JkThirdOrder 三方订单表
type JkThirdOrder struct {
	ID                int64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:主键ID" json:"id"`                    // 主键ID
	JkShopID          int64     `gorm:"column:jk_shop_id;not null;comment:jekka店铺ID" json:"jk_shop_id"`                    // jekka店铺ID
	ThirdType         int32     `gorm:"column:third_type;not null;comment:店铺类型" json:"third_type"`                         // 店铺类型
	JkUserID          int64     `gorm:"column:jk_user_id;not null;comment:jekka主账号ID" json:"jk_user_id"`                   // jekka主账号ID
	OrderID           string    `gorm:"column:order_id;not null;comment:订单号" json:"order_id"`                              // 订单号
	Price             float64   `gorm:"column:price;not null;comment:订单价格" json:"price"`                                   // 订单价格
	BuyerUserID       string    `gorm:"column:buyer_user_id;not null;comment:买家用户ID" json:"buyer_user_id"`                 // 买家用户ID
	OrderStatus       string    `gorm:"column:order_status;not null;comment:订单状态" json:"order_status"`                     // 订单状态
	BuyerNote         string    `gorm:"column:buyer_note;not null;comment:买家备注" json:"buyer_note"`                         // 买家备注
	BuyerEmail        string    `gorm:"column:buyer_email;not null;comment:买家邮箱" json:"buyer_email"`                       // 买家邮箱
	PaymentMethod     string    `gorm:"column:payment_method;not null;comment:支付方式" json:"payment_method"`                 // 支付方式
	TrackingNumber    string    `gorm:"column:tracking_number;comment:追踪单号" json:"tracking_number"`                        // 追踪单号
	ShippingProvider  string    `gorm:"column:shipping_provider;comment:运输商提供商name" json:"shipping_provider"`              // 运输商提供商name
	CancelReason      string    `gorm:"column:cancel_reason;comment:取消原因" json:"cancel_reason"`                            // 取消原因
	JkSellerNote      string    `gorm:"column:jk_seller_note;not null;comment:jk侧卖家备注" json:"jk_seller_note"`              // jk侧卖家备注
	JkOperatorRecords string    `gorm:"column:jk_operator_records;not null;comment:jekka侧操作记录" json:"jk_operator_records"` // jekka侧操作记录
	CreateTime        int64     `gorm:"column:create_time;not null;comment:创建时间戳" json:"create_time"`                      // 创建时间戳
	UpdateTime        int64     `gorm:"column:update_time;not null;comment:更新时间戳" json:"update_time"`                      // 更新时间戳
	CreatedAt         time.Time `gorm:"column:created_at;not null" json:"created_at"`
	UpdatedAt         time.Time `gorm:"column:updated_at;not null" json:"updated_at"`
}

// TableName JkThirdOrder's table name
func (*JkThirdOrder) TableName() string {
	return TableNameJkThirdOrder
}
