// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameJkThirdOrderExtra = "jk_third_order_extra"

// JkThirdOrderExtra 三方订单扩展信息表
type JkThirdOrderExtra struct {
	ID        int64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:主键ID" json:"id"`  // 主键ID
	JkShopID  int64     `gorm:"column:jk_shop_id;not null;comment:jekka店铺ID" json:"jk_shop_id"`  // jekka店铺ID
	ThirdType int32     `gorm:"column:third_type;not null;comment:店铺类型" json:"third_type"`       // 店铺类型
	JkUserID  int64     `gorm:"column:jk_user_id;not null;comment:jekka主账号ID" json:"jk_user_id"` // jekka主账号ID
	OrderID   string    `gorm:"column:order_id;not null;comment:三方订单号" json:"order_id"`          // 三方订单号
	Extra     string    `gorm:"column:extra;comment:Tiktok/Shopee/Lazada 特有字段" json:"extra"`     // Tiktok/Shopee/Lazada 特有字段
	CreatedAt time.Time `gorm:"column:created_at;not null" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at;not null" json:"updated_at"`
}

// TableName JkThirdOrderExtra's table name
func (*JkThirdOrderExtra) TableName() string {
	return TableNameJkThirdOrderExtra
}
