// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameJkThirdOrderDetail = "jk_third_order_detail"

// JkThirdOrderDetail 三方订单商品详情表
type JkThirdOrderDetail struct {
	ID              int64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:主键ID" json:"id"`               // 主键ID
	JkShopID        int64     `gorm:"column:jk_shop_id;not null;comment:jekka店铺ID" json:"jk_shop_id"`               // jekka店铺ID
	ThirdType       int32     `gorm:"column:third_type;not null;comment:店铺类型" json:"third_type"`                    // 店铺类型
	JkUserID        int64     `gorm:"column:jk_user_id;not null;comment:jekka主账号ID" json:"jk_user_id"`              // jekka主账号ID
	JkOrderID       string    `gorm:"column:jk_order_id;not null;comment:jekka订单合并ID" json:"jk_order_id"`           // jekka订单合并ID
	OrderID         string    `gorm:"column:order_id;not null;comment:三方订单号" json:"order_id"`                       // 三方订单号
	Status          string    `gorm:"column:status;not null;comment:订单状态" json:"status"`                            // 订单状态
	ItemID          string    `gorm:"column:item_id;not null;comment:订单itemID" json:"item_id"`                      // 订单itemID
	ProductName     string    `gorm:"column:product_name;not null;comment:商品名称" json:"product_name"`                // 商品名称
	ProductID       string    `gorm:"column:product_id;not null;comment:商品ID" json:"product_id"`                    // 商品ID
	Sku             string    `gorm:"column:sku;not null;comment:sku" json:"sku"`                                   // sku
	SkuName         string    `gorm:"column:sku_name;not null;comment:sku名称" json:"sku_name"`                       // sku名称
	SkuImageURL     string    `gorm:"column:sku_image_url;comment:skuUrl" json:"sku_image_url"`                     // skuUrl
	ProductURL      string    `gorm:"column:product_url;comment:商品Url" json:"product_url"`                          // 商品Url
	TrackingNumber  string    `gorm:"column:tracking_number;not null;comment:订单号" json:"tracking_number"`           // 订单号
	DiscountedPrice float64   `gorm:"column:discounted_price;not null;comment:订单价格（折扣后价格）" json:"discounted_price"` // 订单价格（折扣后价格）
	OriginalPrice   float64   `gorm:"column:original_price;not null;comment:商品原价" json:"original_price"`            // 商品原价
	Currency        string    `gorm:"column:currency;not null;comment:货币" json:"currency"`                          // 货币
	Qty             int32     `gorm:"column:qty;not null;comment:商品购买数量" json:"qty"`                                // 商品购买数量
	Item            string    `gorm:"column:item;not null;comment:订单行其他商品信息" json:"item"`                           // 订单行其他商品信息
	CreatedAt       time.Time `gorm:"column:created_at;not null" json:"created_at"`
	UpdatedAt       time.Time `gorm:"column:updated_at;not null" json:"updated_at"`
}

// TableName JkThirdOrderDetail's table name
func (*JkThirdOrderDetail) TableName() string {
	return TableNameJkThirdOrderDetail
}
