// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameJkThirdReturnOrder = "jk_third_return_order"

// JkThirdReturnOrder 三方订单退货表
type JkThirdReturnOrder struct {
	ID                       int64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"`                                // ID
	JkShopID                 int64     `gorm:"column:jk_shop_id;not null;comment:jk店铺ID" json:"jk_shop_id"`                                 // jk店铺ID
	ThirdType                int32     `gorm:"column:third_type;not null;comment:店铺类型" json:"third_type"`                                   // 店铺类型
	JkUserID                 int64     `gorm:"column:jk_user_id;not null;comment:店铺主账号ID" json:"jk_user_id"`                                // 店铺主账号ID
	OrderID                  string    `gorm:"column:order_id;not null;comment:订单ID" json:"order_id"`                                       // 订单ID
	ReturnID                 string    `gorm:"column:return_id;not null;comment:退货/取消ID" json:"return_id"`                                  // 退货/取消ID
	ReverseOrderLineID       int64     `gorm:"column:reverse_order_line_id;not null;comment:子退货退款单号，不是主单号" json:"reverse_order_line_id"`    // 子退货退款单号，不是主单号
	ReturnType               string    `gorm:"column:return_type;not null;comment:退货/取消类型" json:"return_type"`                              // 退货/取消类型
	Status                   string    `gorm:"column:status;not null;comment:退货/取消状态" json:"status"`                                        // 退货/取消状态
	Reason                   string    `gorm:"column:reason;not null;comment:取消原因" json:"reason"`                                           // 取消原因
	ReasonText               string    `gorm:"column:reason_text;not null;comment:取消原因多语言" json:"reason_text"`                              // 取消原因多语言
	TrackingNumber           string    `gorm:"column:tracking_number;not null;comment:退货单号" json:"tracking_number"`                         // 退货单号
	RefundAmount             string    `gorm:"column:refund_amount;not null;comment:退款总金额" json:"refund_amount"`                            // 退款总金额
	NegotiationStatus        string    `gorm:"column:negotiation_status;not null;comment:协商状态" json:"negotiation_status"`                   // 协商状态
	SellerCompensationStatus string    `gorm:"column:seller_compensation_status;not null;comment:卖家赔偿状态" json:"seller_compensation_status"` // 卖家赔偿状态
	SellerProofStatus        string    `gorm:"column:seller_proof_status;not null;comment:卖家证据状态" json:"seller_proof_status"`               // 卖家证据状态
	LogisticsStatus          string    `gorm:"column:logistics_status;not null;comment:物流状态" json:"logistics_status"`                       // 物流状态
	BuyerUserID              int64     `gorm:"column:buyer_user_id;comment:买家ID" json:"buyer_user_id"`                                      // 买家ID
	JkOperatorRecords        string    `gorm:"column:jk_operator_records;not null;comment:jekka侧操作记录" json:"jk_operator_records"`           // jekka侧操作记录
	Extra                    string    `gorm:"column:extra;comment:Tiktok/Shopee/Lazada 特有字段" json:"extra"`                                 // Tiktok/Shopee/Lazada 特有字段
	CreateTime               int64     `gorm:"column:create_time;not null" json:"create_time"`
	UpdateTime               int64     `gorm:"column:update_time;not null" json:"update_time"`
	CreatedAt                time.Time `gorm:"column:created_at" json:"created_at"`
	UpdatedAt                time.Time `gorm:"column:updated_at" json:"updated_at"`
}

// TableName JkThirdReturnOrder's table name
func (*JkThirdReturnOrder) TableName() string {
	return TableNameJkThirdReturnOrder
}
