// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameJkThirdProduct = "jk_third_product"

// JkThirdProduct 三方商品同步信息表
type JkThirdProduct struct {
	ID           int64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:主键ID" json:"id"`       // 主键ID
	JkShopID     int64     `gorm:"column:jk_shop_id;not null;comment:jekka店铺ID" json:"jk_shop_id"`       // jekka店铺ID
	ProductID    string    `gorm:"column:product_id;not null;default:0;comment:产品 ID" json:"product_id"` // 产品 ID
	Title        string    `gorm:"column:title;not null;comment:产品标题" json:"title"`                      // 产品标题
	Description2 string    `gorm:"column:description2;comment:产品描述" json:"description2"`                 // 产品描述
	MinPrice     float64   `gorm:"column:min_price;not null;default:0.00;comment:最小价格" json:"min_price"` // 最小价格
	MaxPrice     float64   `gorm:"column:max_price;not null;default:0.00;comment:最大价格" json:"max_price"` // 最大价格
	Handle       string    `gorm:"column:handle;comment:Handel字段 shopify 专用" json:"handle"`              // Handel字段 shopify 专用
	Options      string    `gorm:"column:options;comment:选项" json:"options"`                             // 选项
	Currency     string    `gorm:"column:currency;comment:货币代码" json:"currency"`                         // 货币代码
	Skus         string    `gorm:"column:skus;comment:sku集合信息" json:"skus"`                              // sku集合信息
	StockStatus  int32     `gorm:"column:stock_status;not null;comment:库存状态" json:"stock_status"`        // 库存状态
	PreOrder     int32     `gorm:"column:pre_order;not null;comment:是否预售;0:非预售;1:预售" json:"pre_order"`   // 是否预售;0:非预售;1:预售
	CategoryID   int64     `gorm:"column:category_id;comment:商品分类 id" json:"category_id"`                // 商品分类 id
	URL          string    `gorm:"column:url;comment:商品 url" json:"url"`                                 // 商品 url
	ImageURL     string    `gorm:"column:image_url;comment:缩略图 url" json:"image_url"`                    // 缩略图 url
	SellerSkus   string    `gorm:"column:seller_skus;comment:skus名称集合字符，es查询使用" json:"seller_skus"`      // skus名称集合字符，es查询使用
	SkuIds       string    `gorm:"column:sku_ids;comment:skusId集合字符，es查询使用" json:"sku_ids"`              // skusId集合字符，es查询使用
	CreateTime   time.Time `gorm:"column:create_time;not null;comment:商品创建时间戳" json:"create_time"`       // 商品创建时间戳
	CreatedAt    time.Time `gorm:"column:created_at;not null" json:"created_at"`
	UpdatedAt    time.Time `gorm:"column:updated_at;not null" json:"updated_at"`
	Test         string    `gorm:"column:test" json:"test"`
}

// TableName JkThirdProduct's table name
func (*JkThirdProduct) TableName() string {
	return TableNameJkThirdProduct
}
