// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameJkThirdReturnOrderDetail = "jk_third_return_order_detail"

// JkThirdReturnOrderDetail 三方订单退货明细表
type JkThirdReturnOrderDetail struct {
	ID                   int64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"`                                                          // ID
	JkThirdReturnOrderID int64     `gorm:"column:jk_third_return_order_id;not null;comment:三方订单退货表id" json:"jk_third_return_order_id"`                            // 三方订单退货表id
	SkuID                int64     `gorm:"column:sku_id;not null;comment:sku" json:"sku_id"`                                                                      // sku
	SkuName              string    `gorm:"column:sku_name;not null;comment:sku名称" json:"sku_name"`                                                                // sku名称
	ProductID            int64     `gorm:"column:product_id;not null;comment:商品id" json:"product_id"`                                                             // 商品id
	ProductName          string    `gorm:"column:product_name;not null;comment:商品名称" json:"product_name"`                                                         // 商品名称
	Currency             string    `gorm:"column:currency;not null;comment:货币" json:"currency"`                                                                   // 货币
	Quantity             int32     `gorm:"column:quantity;not null;comment:数量" json:"quantity"`                                                                   // 数量
	Price                string    `gorm:"column:price;not null;default:0;comment:价格，货币单位为分，越南盾除外（例如，对于 SG，100 等于 1 新加坡元；对于 VN，10000 等于 10000 越南盾）" json:"price"` // 价格，货币单位为分，越南盾除外（例如，对于 SG，100 等于 1 新加坡元；对于 VN，10000 等于 10000 越南盾）
	DiscountAmount       string    `gorm:"column:discount_amount;not null;default:0;comment:退款折扣金额" json:"discount_amount"`                                       // 退款折扣金额
	RefundAmount         string    `gorm:"column:refund_amount;not null;default:0;comment:退款金额" json:"refund_amount"`                                             // 退款金额
	ProductImage         string    `gorm:"column:product_image;not null;comment:商品图片" json:"product_image"`                                                       // 商品图片
	CreateTime           int64     `gorm:"column:create_time;not null" json:"create_time"`
	UpdateTime           int64     `gorm:"column:update_time;not null" json:"update_time"`
	CreatedAt            time.Time `gorm:"column:created_at" json:"created_at"`
	UpdatedAt            time.Time `gorm:"column:updated_at" json:"updated_at"`
}

// TableName JkThirdReturnOrderDetail's table name
func (*JkThirdReturnOrderDetail) TableName() string {
	return TableNameJkThirdReturnOrderDetail
}
