// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameJkUser = "jk_user"

// JkUser mapped from table <jk_user>
type JkUser struct {
	ID                int64          `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"`                   // ID
	BizType           int32          `gorm:"column:biz_type;not null;comment:账号业务类型 0:未选择，1:完整功能，2:智能跟单" json:"biz_type"`    // 账号业务类型 0:未选择，1:完整功能，2:智能跟单
	ParentID          int64          `gorm:"column:parent_id;not null;comment:父用户ID" json:"parent_id"`                       // 父用户ID
	UserNo            string         `gorm:"column:user_no;not null;comment:用户编号" json:"user_no"`                            // 用户编号
	Email             string         `gorm:"column:email;not null;comment:邮箱" json:"email"`                                  // 邮箱
	Username          string         `gorm:"column:username;not null;comment:用户名" json:"username"`                           // 用户名
	Nickname          string         `gorm:"column:nickname;not null;comment:昵称" json:"nickname"`                            // 昵称
	SourceType        int32          `gorm:"column:source_type;not null;comment:用户来源;0:默认;1:有赞" json:"source_type"`          // 用户来源;0:默认;1:有赞
	ThirdUserID       int64          `gorm:"column:third_user_id;not null;comment:用户的三方id" json:"third_user_id"`             // 用户的三方id
	Pwd               string         `gorm:"column:pwd;not null;comment:密码" json:"pwd"`                                      // 密码
	Status            int32          `gorm:"column:status;not null;default:1;comment:用户状态 0:无效的 1:有效的" json:"status"`        // 用户状态 0:无效的 1:有效的
	AiStatus          int32          `gorm:"column:ai_status;default:1;comment:AiBot状态 0:关闭 1:打开" json:"ai_status"`          // AiBot状态 0:关闭 1:打开
	InviteCode        string         `gorm:"column:invite_code;comment:邀请码" json:"invite_code"`                              // 邀请码
	AssignLimit       int32          `gorm:"column:assign_limit;not null;default:9999;comment:会话分配数量上限" json:"assign_limit"` // 会话分配数量上限
	Token             string         `gorm:"column:token;not null;comment:访问口令" json:"token"`                                // 访问口令
	ExpiredAt         time.Time      `gorm:"column:expired_at;comment:访问口令有效期（NULL表示无有效期）" json:"expired_at"`                // 访问口令有效期（NULL表示无有效期）
	EmailAssignStatus int32          `gorm:"column:email_assign_status;comment:邮件分配状态 0:关闭 1:打开" json:"email_assign_status"` // 邮件分配状态 0:关闭 1:打开
	PhoneCode         string         `gorm:"column:phone_code;not null;comment:拨号前缀" json:"phone_code"`                      // 拨号前缀
	PhoneNumber       string         `gorm:"column:phone_number;not null;comment:电话号码" json:"phone_number"`                  // 电话号码
	CompanyName       string         `gorm:"column:company_name;not null;comment:公司名称" json:"company_name"`                  // 公司名称
	CreatedAt         time.Time      `gorm:"column:created_at" json:"created_at"`
	UpdatedAt         time.Time      `gorm:"column:updated_at" json:"updated_at"`
	DeletedAt         gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
}

// TableName JkUser's table name
func (*JkUser) TableName() string {
	return TableNameJkUser
}
